name: ProjectEuler
description: An app interface to the Project Euler problems.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  html: ^0.14.0+3
  http: ^0.12.0+4
  floor: ^0.12.0
  provider: ^3.0.0
  shared_preferences: ^0.5.6+3
  scoped_model: ^1.0.1
  webview_flutter: ^0.3.19+9
  share: ^0.6.3+6
  cupertino_icons: ^0.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  floor_generator: ^0.12.0
  build_runner: ^1.7.3

flutter:
  uses-material-design: true
